### ISSUE TITLE
苹果手机无法进行联机

### ISSUE THREAD

**Issue by Mrcober** [RainEggplant/noname-pwa#3]
![71a5fc3574727dbd3a5f3672a745bec](https://github.com/RainEggplant/noname-pwa/assets/70991858/44068a1e-47cb-4776-8190-f8c35f854e71)
系统版本：ios17.3.1
浏览器：Safari
问题：ios17 NSURLSession WebSocket在开发者选项中已经移除，私人服务器无法进行联机
补充：在安卓上测试过服务器可以正常进入

**Comment by RainEggplant** [comment]
Sorry, 我手里没有 ios 17 的设备，没法进行测试。不过，按理来说新系统的这个选项应该是默认打开的（移除应该只是隐藏了）。你确认服务器使用的是加密 wss 而不是 ws 连接吗？如果服务器是 ws 而你本地用了 wss 去连（不写明协议默认是 wss）就可能出现上图的情况。

**Comment by Mrcober** [comment]
服务器确认是ws连接，那么请问如何解决不能联机的问题呢，我在选项里关闭使用wss连接也无法进行联机

**Comment by RainEggplant** [comment]
> 服务器确认是ws连接，那么请问如何解决不能联机的问题呢，我在选项里关闭使用wss连接也无法进行联机

Safari 会[阻止混合内容](https://github.com/RainEggplant/noname-pwa/blob/master/allow_mixed_content.md)，但我不清楚 ios 上有没有可以允许加载混合内容的浏览器。我建议给要么给服务器搞个域名+免费证书，使用 wss 连接；要么自己部署一个 http 版本的网页端，使用 ws 连接。
